version: '3.3'

services:
  go:
    build: 
      context: ./go
      dockerfile: Dockerfile
    image: maxmcd/wasm-servers:go
    volumes: 
      - shared:/go/src/github.com/maxmcd/wasm-servers/shared/
  go-print:
    build:
      context: ./programs/go-print
      dockerfile: Dockerfile
    image: maxmcd/wasm-servers:go-print
    volumes: 
      - shared:/go/src/github.com/maxmcd/wasm-servers/shared/
  go-fs:
    build:
      context: ./programs/go-fs
      dockerfile: Dockerfile
    image: maxmcd/wasm-servers:go-fs
    volumes: 
      - shared:/go/src/github.com/maxmcd/wasm-servers/shared/
  go-net:
    build:
      context: ./programs/go-net
      dockerfile: Dockerfile
    image: maxmcd/wasm-servers:go-net
    volumes: 
      - shared:/go/src/github.com/maxmcd/wasm-servers/shared/
  runtime:
    build:
      context: ./runtime
      dockerfile: Dockerfile
    image: maxmcd/wasm-servers:runtime
    volumes: 
      - shared:/opt/shared/
      - /home/ubuntu/runtime-src:/opt/runtime/src/
      - target:/opt/runtime/target/

volumes:
  shared:
  target:
