# we need memory limits, they're only available in 2.*
version: '2'

services:
  runtime:
    build:
      context: ./cmd/runtime
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:runtime
  switch-bug-test-case:
    build:
      context: ./cmd
      dockerfile: ./switch-bug-test-case/Dockerfile
  switch-bug-test-case-node:
    build:
      context: ./cmd
      dockerfile: ./switch-bug-test-case/node.Dockerfile
  circleci:
    build:
      context: ./cmd/circleci-runner
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:circleci
  go:
    build:
      context: ./pkg/go/
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:go
  gowasm:
    build:
      context: ./
      dockerfile: ./pkg/gowasm/Dockerfile
    image: maxmcd/wasm-servers:go-wasm-lib
  go-fs:
    build:
      context: ./cmd
      dockerfile: ./go-fs/Dockerfile
    image: maxmcd/wasm-servers:go-fs
  rust-basic:
    build:
      context: ./cmd/rust-basic
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:rust-basic
