version: 2

jobs:
  build:
    docker:
      - image: maxmcd/wasm-servers:circleci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: print done
          command: |
            echo done
