version: 2

jobs:
  build:
    docker:
      - image: maxmcd/wasm-servers:circleci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build go
          command: |
            docker-compose build go
      - run:
          name: build go-fs
          command: |
            docker-compose build go-fs
            docker-compose run go-fs
      - run:
          name: build gowasm
          command: |
            docker-compose build gowasm
            docker-compose run gowasm
